import { ProjectGenres, ProjectTones, ProjectGenre, ProjectTone } from "@/features/projects/interfaces/projects.interfaces";

export const GenreOptions: { label: string; value: ProjectGenre }[] = [
    { label: "Action", value: ProjectGenres.ACTION },
    { label: "Adventure", value: ProjectGenres.ADVENTURE },
    { label: "Animation", value: ProjectGenres.ANIMATION },
    { label: "Comedy", value: ProjectGenres.COMEDY },
    { label: "Crime", value: ProjectGenres.CRIME },
    { label: "Documentary", value: ProjectGenres.DOCUMENTARY },
    { label: "Drama", value: ProjectGenres.DRAMA },
    { label: "Fantasy", value: ProjectGenres.FANTASY },
    { label: "Historical", value: ProjectGenres.HISTORICAL },
    { label: "Horror", value: ProjectGenres.HORROR },
    { label: "Mystery", value: ProjectGenres.MYSTERY },
    { label: "Romance", value: ProjectGenres.ROMANCE },
    { label: "Sci-Fi", value: ProjectGenres.SCI_FI },
    { label: "Thriller", value: ProjectGenres.THRILLER },
    { label: "Western", value: ProjectGenres.WESTERN },
    { label: "Experimental", value: ProjectGenres.EXPERIMENTAL },
];

export const ToneOptions: { label: string; value: ProjectTone }[] = [
    { label: "Dark", value: ProjectTones.DARK },
    { label: "Lighthearted", value: ProjectTones.LIGHTHEARTED },
    { label: "Gritty", value: ProjectTones.GRITTY },
    { label: "Epic", value: ProjectTones.EPIC },
    { label: "Hopeful", value: ProjectTones.HOPEFUL },
    { label: "Melancholic", value: ProjectTones.MELANCHOLIC },
    { label: "Romantic", value: ProjectTones.ROMANTIC },
    { label: "Suspenseful", value: ProjectTones.SUSPENSEFUL },
    { label: "Mysterious", value: ProjectTones.MYSTERIOUS },
    { label: "Inspirational", value: ProjectTones.INSPIRATIONAL },
    { label: "Comedic", value: ProjectTones.COMEDIC },
    { label: "Serious", value: ProjectTones.SERIOUS },
    { label: "Satirical", value: ProjectTones.SATIRICAL },
    { label: "Intense", value: ProjectTones.INTENSE },
    { label: "Whimsical", value: ProjectTones.WHIMSICAL },
];

export const GenreOptionsLabels = {
    [ProjectGenres.ACTION]: "Action",
    [ProjectGenres.ADVENTURE]: "Adventure",
    [ProjectGenres.ANIMATION]: "Animation",
    [ProjectGenres.COMEDY]: "Comedy",
    [ProjectGenres.CRIME]: "Crime",
    [ProjectGenres.DOCUMENTARY]: "Documentary",
    [ProjectGenres.DRAMA]: "Drama",
    [ProjectGenres.FANTASY]: "Fantasy",
    [ProjectGenres.HISTORICAL]: "Historical",
    [ProjectGenres.HORROR]: "Horror",
    [ProjectGenres.MYSTERY]: "Mystery",
    [ProjectGenres.ROMANCE]: "Romance",
    [ProjectGenres.SCI_FI]: "Sci-Fi",
    [ProjectGenres.THRILLER]: "Thriller",
    [ProjectGenres.WESTERN]: "Western",
    [ProjectGenres.EXPERIMENTAL]: "Experimental",
}

export const ToneOptionsLabels = {
    [ProjectTones.DARK]: "Dark",
    [ProjectTones.LIGHTHEARTED]: "Lighthearted",
    [ProjectTones.GRITTY]: "Gritty",
    [ProjectTones.EPIC]: "Epic",
    [ProjectTones.HOPEFUL]: "Hopeful",
    [ProjectTones.MELANCHOLIC]: "Melancholic",
    [ProjectTones.ROMANTIC]: "Romantic",
    [ProjectTones.SUSPENSEFUL]: "Suspenseful",
    [ProjectTones.MYSTERIOUS]: "Mysterious",
    [ProjectTones.INSPIRATIONAL]: "Inspirational",
    [ProjectTones.COMEDIC]: "Comedic",
    [ProjectTones.SERIOUS]: "Serious",
    [ProjectTones.SATIRICAL]: "Satirical",
    [ProjectTones.INTENSE]: "Intense",
    [ProjectTones.WHIMSICAL]: "Whimsical",
}